### ISSUE TITLE
Compilation error with simple example

### ISSUE THREAD

**Issue by Matheus-Garbelini** [veselink1/refl-cpp#17]
Hi, I was trying to perform a simple example but I am receiving a lot of errors during compilation.
I'm using gcc/g++ 8.4.0 and compiling the program with the following command:
`g++ -std=c++17 -Wall -g main.cpp -o test`

```C++
#define REFL_METADATA_FILE "reflmd/main.cpp"
#include "libs/refl.hpp"
#include <iostream>

struct pdu_types_struct
{
    REFL() // the reflmd file has been generated
    int var1= 28;
};

struct pdu_types_struct pdu_types;

int main(int argc, char **argv)
{
     for_each(refl::reflect(pdu_types).members, [&](auto member) {
      std::cout << member.name << "=" << member(pdu_types) << ";";
   });
    return 0;
} 

#include REFL_METADATA_FILE
```

With the code above, I receive the following errors:

```shell
g++ -std=c++17 -Wall -g main.cpp -o test   
In file included from main.cpp:2:
libs/refl.hpp: In instantiation of ‘class refl::descriptor::type_descriptor<pdu_types_struct>’:
main.cpp:15:38:   required from here
libs/refl.hpp:1625:27: error: static assertion failed: This type does not support reflection!
             static_assert(refl::trait::is_reflectable_v<T>, "This type does not support reflection!");
                           ^~~~
libs/refl.hpp:2620:55: error: specialization of ‘refl_impl::metadata::type_info__<pdu_types_struct>’ after instantiation
     namespace refl_impl::metadata { template<> struct type_info__<TypeName> { \
                                                       ^~~~~~~~~~~~~~~~~~~~~
reflmd/main.cpp:3:1: note: in expansion of macro ‘REFL_TYPE’
 REFL_TYPE(pdu_types_struct)
 ^~~~~~~~~
libs/refl.hpp:2620:55: error: redefinition of ‘struct refl_impl::metadata::type_info__<pdu_types_struct>’
     namespace refl_impl::metadata { template<> struct type_info__<TypeName> { \
                                                       ^~~~~~~~~~~~~~~~~~~~~
reflmd/main.cpp:3:1: note: in expansion of macro ‘REFL_TYPE’
 REFL_TYPE(pdu_types_struct)
 ^~~~~~~~~
In file included from main.cpp:2:
libs/refl.hpp:373:20: note: previous definition of ‘struct refl_impl::metadata::type_info__<pdu_types_struct>’
             struct type_info__

```

Is there some pre step to use the library I am missing or some additional argument when calling g++?

Regards

**Comment by veselink1** [comment]
Hello,

I assume you are running `refl-ht -input=main.cpp` beforehand? The preprocessor hasn't been updated to work with recent refl-cpp versions as there are some issues which cannot be solved without rewriting the whole thing are creating more work than I can manage at the moment.

**Comment by veselink1** [comment]
I would suggest that you go the usual route of using `REFL_AUTO` or the `REFL_TYPE/FIELD` macros as that is currently fully supported.
In your case you would need to remove the `REFL_METADATA_FILE` and `REFL()` lines and add something like the following after the struct definition. 
```cpp
REFL_AUTO(
    type(pdu_types_struct),
    field(var1)
)
```

**Comment by Matheus-Garbelini** [comment]
@veselink1 thanks for your reply. I was indeed using refl-ht beforehand.
using the REFL_AUTO instead of the refl-ht preprocessor worked fine. 
However, the file that refl-ht seems to be fine. It generates a main.cpp like this:

REFL_TYPE(pdu_types_struct)
	REFL_FIELD(var1)
REFL_END

If I use the old refl-cpp style and copy this block in my code, it works fine.
For some reason, just by including this on a separate file seems to be generating all these errors. By digging further, I was able to confirm that just by placing the REFL reflection definition on bottom of the source code, we receive many errors such as "This type does not support reflection".

In short, this does not work:
```C++
#include "libs/refl.hpp"
#include <iostream>

struct pdu_types_struct
{
    int var1= 28;
};

struct pdu_types_struct pdu_types;

int main(int argc, char **argv)
{
     for_each(refl::reflect(pdu_types).members, [&](auto member) {
      std::cout << member.name << "=" << member(pdu_types) << ";" << std::endl;
   });
    return 0;
} 

REFL_AUTO(
    type(pdu_types_struct),
    field(var1)
)
``` 


But this works:
```C++
#include "libs/refl.hpp"
#include <iostream>

struct pdu_types_struct
{
    int var1= 28;
};

REFL_AUTO(
    type(pdu_types_struct),
    field(var1)
)

struct pdu_types_struct pdu_types;

int main(int argc, char **argv)
{
     for_each(refl::reflect(pdu_types).members, [&](auto member) {
      std::cout << member.name << "=" << member(pdu_types) << ";" << std::endl;
   });
    return 0;
} 

```

Thanks a lot and great project.

**Comment by Matheus-Garbelini** [comment]
Just chaining another question. What is the simplest way (low overhead) way to get a member name to a string or preferable a char array (char *)?
Currently, I'm only able to get a string to making this costly operation inside the foreach loop:
```C++
 stringstream s("");
 s << member.name;
```

**Comment by veselink1** [comment]
Thank you for taking the time to look into what the specific issue is. That seems to be happening because the template-specializations created by the `REFL_AUTO` macro are not available at the point of usage in `main()`. Reflection information should ideally be defined right after the type definition.

**Comment by veselink1** [comment]
To get a `cosnt char*` from a `const_string<N>` one could use [const_string<N>::c_str()](https://veselink1.github.io/refl-cpp/structrefl_1_1util_1_1const__string.html#a465086c5ae8e245358ce44ed8154c986).

**Comment by veselink1** [comment]
I'm closing this as refl-ht has been discontinued.
