### ISSUE TITLE
example-serialize  has 3 error

### ISSUE THREAD

**Issue by runner0353** [veselink1/refl-cpp#18]
clang++ example-serialization.cpp -o example-serialization -std=c++17 -I ./../
In file included from example-serialization.cpp:10:
./../refl.hpp:1715:72: error: too few template arguments for class template 'debug'
            struct is_instance_of<T, U<Args...>> : public std::is_same<T<Args...>, U<Args...>>
                                                                       ^
./../refl.hpp:1725:33: note: in instantiation of template class 'refl::trait::detail::is_instance_of<debug, refl::attr::base_types<> >' requested here
        struct is_instance_of : detail::is_instance_of<T, U>
                                ^
./../refl.hpp:1734:66: note: in instantiation of template class 'refl::trait::is_instance_of<debug, refl::attr::base_types<> >' requested here
        [[maybe_unused]] static constexpr bool is_instance_of_v{ is_instance_of<T, U>::value };
                                                                 ^
./../refl.hpp:1899:42: note: in instantiation of variable template specializatio
How to solve the problem of serial compilation？I use g ++ to compile the same

**Comment by veselink1** [comment]
Hello,

This seemed to be caused by an incorrect implementation of `is_instance_of`. Are you able to successfully run the example with the referenced commit?

**Comment by runner0353** [comment]
In addition to the serialization example, other examples can be passed
