### ISSUE TITLE
Is it possible to get at nested member objects ?

### ISSUE THREAD

**Issue by lenkite** [veselink1/refl-cpp#41]
Thinking of writing a template engine (moustache) that can  interpolate struct values into templates. However, it would be necessary to get at the values of nested member objects by name. Is it possible to do this using refl-cpp ? 
Basically to permit something like  `{{p.addr.city}}`

```cpp
    struct address {
        std::string city;
    };

    struct person {
        address addr;
    };
```

**Comment by ccvca** [comment]
If both, `person` and `address`, are reflectable, it's possible using recursion.  (Call reflect on p and look for addr, then reflect addr and look for city).
