### ISSUE TITLE
Port to vcpkg

### ISSUE THREAD

**Issue by al-sabr** [veselink1/refl-cpp#62]
Please port this header library to vcpkg.

Thanx

**Comment by veselink1** [comment]
https://github.com/microsoft/vcpkg/blob/master/ports/refl-cpp/vcpkg.json
refl-cpp is available on vcpkg. Is there a problem with the package? Thanks.

**Comment by veselink1** [comment]
It is now mentioned in the README

**Comment by al-sabr** [comment]
It's great! Thank you!
