### ISSUE TITLE
Q: how to reflect on member functions' parameters and return types?

### ISSUE THREAD

**Issue by RalphSteinhagen** [veselink1/refl-cpp#69]
We are using refl-cpp primarily for reflections on member fields which works perfectly fine for our use case.

We may have a new application now, where I was wondering whether this could be also extended also to member functions, notably to retrieve their parameter and return type signatures during compile time.

For example, having the following demo class definition:
```cpp
class Circle {
    double r;
public:
    Circle(double val) : r(val) {}
    double getRadius() const { return r; }
    void setRadius(double radius) { r = radius; }
    std::string getFunc(int a, double b, std::string c) const { return fmt::format("{}{}{}",a,b,c); }
    double getDiameter() const { return 2 * r; }
    double getArea() const { return M_PI * r * r; }
};
````

How would one go about retrieving the `setRadius(double)` calling parameter (double) and return value (void)? Or, more generally, the number of calling parameters of `getFunc(...)`  which would be `std::tuple<int,double,std::string>` and its return type `std::string`?

There is an example that illustrates how to get the function pointer and how to call 'std::invoke(..)` but this seems to implicitly assume the calling parameter and return types:

```cpp
using refl::reflect;
using refl::util::find_one;
constexpr auto type = reflect<Circle>();
 
constexpr auto func = find_one(type.members, [](auto m) { return m.name == "getRadius"; }); // -> function_descriptor<Circle, 0>{...}

func.name; // -> const_string<6>{"getRadius"}
func.attributes; // -> std::tuple<>{}
func.is_resolved; // -> true
func.pointer; // -> pointer of type double (Circle::* const)()
 
using radius_t = double (Circle::* const)();
func.template resolve<radius_t>; // -> pointer of type radius_t on success, nullptr_t on fail.
 
Circle c(2.0);
func.invoke(c); // -> the result of c.getRadius()
```

Also more generally, how would one register, find and call the different class constructors and parameter signatures?

This (potentially new) functionality has applications in GUIs and other areas where the compile/run-time definitions are driven by configuration files.

Any help, suggestions, or feedback would be welcome. Thanks in advance.

**Comment by RalphSteinhagen** [comment]
Will close this since my initial question has been answered.

**Comment by veselink1** [comment]
Sorry about the typo. Thanks for linking a working example.

> Are these helper functions something that could be potentially also useful for others using refl-cpp?

They could be useful, but I've refrained from adding them because they are available in other libraries in common use (e.g. `function_traits` in boost/type_traits).

FWIW, I don't think it is possible to deduce the argument types of constructors. This works for (member) functions because they are not overloaded and the compiler can deduce the type of the pointer to use in the expression `(&Circle::getRadius)`, but if you think about it, constructors are always overloaded (because of implicitly generated constructors):
- `Circle::Circle(double)`
- `Circle::Circle(const Circle&)`
- `Circle::Circle(Circle&&)`

**Comment by RalphSteinhagen** [comment]
> Sorry about the typo.

No worries, this just seems to confirm that you are human. :smile: 

> They could be useful, but I've refrained from adding them because [..] boost/type_traits.

I fully understand. Keeping the API envelope small eases maintenance.

> FWIW, I don't think it is possible to deduce the argument types of constructors. 

Yes and this isn't critical, because having one default constructor and one constructor with explicit custom attributes declared should work for the targeted application where these classes usually have only a limited number of constructors but potentially many member functions. The application is still in an explorative state but just wanted to check before investing too much in this with an MVP.

In any case, thanks a lot for your feedback!
