### ISSUE TITLE
Regression: Windows compilation broken due to constexpr rules

### ISSUE THREAD

**Issue by Milerius** [veselink1/refl-cpp#8]
https://github.com/veselink1/refl-cpp/commit/469c3c676184deb58b354efa3c4479322b29f87a#diff-9d3b8a5a5ab7d2d06d496a5008d3d3ac

This commit seem's to broke windows compilation:

![image](https://user-images.githubusercontent.com/21139416/65372886-59104180-dc76-11e9-83c9-30153067fe1a.png)

```cpp
/**
             * Explicitly converts to std::string.
             */
            explicit constexpr operator std::string() const noexcept
            {
                return data;
            }
````

This code is illegal because constexpr function cannot return non constexpr type such as `std::string`

**Comment by veselink1** [comment]
Fixed in v0.6.1 / commit [b3138c2](https://github.com/veselink1/refl-cpp/commit/b3138c24b78c5a6d2800837398202f2c005b1b67).
