### ISSUE TITLE
How can I integrate this lib with Eigen3 math lib?

### ISSUE THREAD

**Issue by rocketman123456** [veselink1/refl-cpp#86]
I’m new to this lib and I cannot find a way to reflect eigen matrix

**Comment by veselink1** [comment]
refl-cpp requires you to write metadata definitions for unknown types, such as the types in Eigen. 

Maybe start here:
https://veselink1.github.io/refl-cpp/md__introduction.html#autotoc_md49

**Comment by rocketman123456** [comment]
Thanks a lot! I will update if I make any progress
